// The following directive is necessary to make the package coherent:

// +build ignore

// This program generates emotes_gen.go. It can be invoked by running go generate
package main

import (
	"bufio"
	"log"
	"os"
	"text/template"
	"time"
)

func main() {
	emotes := []string{}

	file, err := os.Open("emotes.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		emotes = append(emotes, scanner.Text())
	}

	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}

	file, err = os.Create("emotes_gen.go")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	packageTemplate.Execute(file, struct {
		Timestamp time.Time
		Emotes    []string
	}{
		Timestamp: time.Now(),
		Emotes:    emotes,
	})
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package cancerigo

var Emotes = [...]string{
{{- range .Emotes }}
	{{ printf "%q" . }},
{{- end }}
}
var EmotesCount = {{ len .Emotes }}
`))
